name: LeasingNinja Kotlin CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
#          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
#      - name: Build with Gradle without tests
#        run:
#          mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true
 #     - name: Build with Maven without Jigsaw
 #       run: |
 #         bin/enable-jigsaw.sh disable
 #         mvn --batch-mode --update-snapshots package
 #         bin/enable-jigsaw.sh enable
