/*
 * This file was generated by the Gradle 'init' task.
 */

 plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    implementation("org.jmolecules:jmolecules-ddd")
    //implementation(project(":utilities"))
}
