/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */

plugins {
    `kotlin-dsl`
    kotlin("jvm") version "1.5.21"
}

tasks.test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

dependencies {
    //"commonMainImplementation"("org.jmolecules:jmolecules-ddd:1.2.0")
     // Other dependencies.
     testImplementation(kotlin("test"))
     testImplementation("io.kotest:kotest-runner-junit5:4.6.1")
}
