name: LeasingNinja Kotlin CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
#          cache: gradle
      - name: Execute Gradle build
        run: ./gradlew build --no-daemon
